@app.route('/model_training', methods=['POST'])
def model_training():
    # ...
    if library == "Sklearn":
        # ...
    elif library == "PyTorch":
        input_size = X_train.shape[1]
        model = model_class(input_size, **hyperparams)
        model.fit(X_train.values, y_train.values)
        y_pred = model.predict(X_train.values)
        # ...
    else:
        # ...
    # ...

@app.route('/model_prediction', methods=['POST'])
def model_prediction():
    # ...
    if library_type == "Sklearn":
        # ...
    elif library_type == "PyTorch":
        y_pred_proba = model.predict(X_phase.values)
        y_pred = (y_pred_proba > 0.5).astype(int)
        # ...
    else:
        # ...
    # ...